export { default as Civil } from './Civil'
export { default as Code } from './CSE'
export { default as Electrical } from './Elect'
export { default as Electronics } from './ENTC'
export { default as Mech } from './Mech'